name: Build & Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate manifest
        run: |
          jq . releases/*/manifest.json > /dev/null
      - name: Generate SHA256 checksums
        run: |
          find releases -type f \( -name '*.svg' -o -name '*.png' -o -name 'manifest.json' \) -exec sha256sum {} \; > SHA256SUMS.txt
      - name: Upload checksums
        uses: actions/upload-artifact@v4
        with:
          name: sha256sums
          path: SHA256SUMS.txt

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: sha256sums
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SHA256SUMS.txt
            releases/*.zip
